config/routes.rb
Rails.application.routes.draw do
  get 'snippets/index'
  devise_for :users
  root to: "snippets#index"
  resources :snippets do 
    member do
      get "delete"
    end
    resources :input_summaries do
    end
  end

  resources :input_summaries do
    resources :templates
    member do
      get "template"
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/input_summary.rb
class InputSummary < ApplicationRecord
  belongs_to :snippet, optional: true
  has_many :templates , dependent: :destroy
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user
  has_many :input_summaries ,dependent: :destroy
  with_options presence: true do
    validates :group_name
    validates :info
  end
end

app/models/template.rb
class Template < ApplicationRecord
  belongs_to :input_summary

  with_options presence: true do
    validates :title 
    validates :info 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :snippets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/input_summaries_controller.rb
class InputSummariesController < ApplicationController
  before_action :set_snippet, only: [:index, :new, :create]

  def index
    @input_summaries = @snippet.input_summaries
  end

  def new
    @input_summary = InputSummary.new
  end

  def create
    @input_summary = InputSummary.new(summary_params)
    if @input_summary.valid?
      @input_summary.save
      redirect_to snippet_input_summaries_path(@snippet.id)
    else
      render :new
    end
  end

  def template
    @input_summary = InputSummary.find(params[:id])
    @snippet = Snippet.find(@input_summary.snippet_id)
    @input_summaries = @snippet.input_summaries
    @template = Template.new

    @templates = @input_summary.templates

    render :index
  end

  private

  def summary_params
    params.require(:input_summary).permit(:summary_name).merge(snippet_id: params[:snippet_id])
  end

  def set_snippet
    @snippet = Snippet.find(params[:snippet_id])
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:edit, :update, :destroy, :delete]
  before_action :user_check, only:[:edit, :update, :destroy]

  def index
    @snippets = Snippet.all.order(created_at: :desc)
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new(snippet_params)
    if @snippet.valid?
      @snippet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit 
    
  end

  def update
    if @snippet.update(snippet_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy 
    if @snippet.user_id == current_user.id
      @snippet.destroy
    end
    redirect_to root_path
  end

  def delete
    
  end

  private

  def set_snippet
    @snippet = Snippet.find(params[:id])
  end

  def user_check
    redirect_to root_path if current_user.id != @snippet.user_id
  end

  def snippet_params
    params.require(:snippet).permit(:group_name, :info).merge(user_id: current_user.id)
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:edit, :update, :destroy]
  
  def create
    @template = Template.new(template_params)
    if @template.save
      flash[:notice] = '追加できました'
      redirect_to template_input_summary_path(@template.input_summary_id)
    else
      flash[:notice] = '追加できません'
      redirect_to template_input_summary_path(@template.input_summary_id)
    end
  end

  def edit
  end

  def update
    if @template.update(template_params)
      redirect_to template_input_summary_path(@template.input_summary_id)
    else
      render :edit
    end
  end

  def destroy
    @template.destroy
    redirect_to template_input_summary_path(@template.input_summary_id)
  end

  private

  def template_params
    params.require(:template).permit(:title, :info).merge(input_summary_id: params[:input_summary_id])
  end

  def set_template
    @template = Template.find(params[:template_id])
    @input_summary = InputSummary.find(params[:input_summary_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/input_summaries_helper.rb
module InputSummariesHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/input_summaries/_main_chat.html.erb
<div id="chat-header">
<% if @template != nil %>
  <%= form_with model: [@input_summary, @template], html: {class: "form"}, local: true do |f|%>
  <div class="form-all">
    <div class="form-input">
      <%= f.text_field :title, class: 'form-title', placeholder: 'タイトルを入力してください' %>
    </div>
    <div class="form-input">
      <%= f.text_area :info, class: 'form-message', placeholder: 'スニペットを入力してください', rows:"7" ,maxlength:"1000" %>
    </div>
    <div class="form-input">
      <%= f.submit '追加', class: 'form-submit' %>
    </div>
    <div class="form-input">
      <div class='back-submit' >戻る</div>
    </div>  
  </div>
  <% end %>
<% end %>
</div>
<div id="messages">
  <%= render partial: 'template', collection: @templates%> 
</div>
<% if @template != nil %>
<div id="text-btn">
  <span class='purchase-btn-text'>Make Up</span>
  <%= image_tag 'search-icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
</div>
<% end %>

app/views/input_summaries/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to '#' do %> 
      <%= @snippet.group_name %> 
    <% end %> 
  </div>
  <div class="all-room">
    <div class="create-room">
      <%= link_to "フォーム追加", new_snippet_input_summary_path(@snippet.id)  %>
    </div>
    <div class="create-room">
      <%= link_to "トップに戻る", root_path  %>
    </div>
  </div>
</div>

<div class="rooms">
  <% @input_summaries.each do |summary| %> 
    <div class="room",data-num-id="<%= summary.id%>"> 

      <% if @input_summary&.id == summary.id %>
        <div class="room-name1">
          <%= link_to summary.summary_name, template_input_summary_path(summary.id) %> 
        </div>
      <% else %>
        <div class="room-name2">
          <%= link_to summary.summary_name, template_input_summary_path(summary.id) %> 
        </div>
      <% end %>

    </div>
  <% end %>
</div>

app/views/input_summaries/_template.html.erb
<div class="message", data-id="<%= template.id%>">
  <div class="upper-message">
    <div class="edit-delete">
      <div class="message-title">タイトル</div>
      <div class="sample-icon">
        <%= link_to edit_input_summary_template_path(@input_summary.id, template_id: template.id) do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to input_summary_template_path(@input_summary.id, template_id: template.id), method: :delete do %>
          <i class="fas fa-trash-alt"></i>   
        <% end %>
      </div>
    </div>
    <div class="message-user">
    <!-- 投稿したユーザー名情報を出力する -->
      <%= template.title%>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-info">内容</div>
    <div class="message-content" , data-id="<%= template.id%>"><textarea class="message-con"><%= template.info%></textarea></div>
  </div>
</div>

app/views/input_summaries/index.html.erb
<div class="wrapper">
  <div class="side-bar"> 
    <%= render "side_bar"%> 
  </div>
  <div class="chat"> 
    <%= render "main_chat" %> 
  </div>
</div>

app/views/input_summaries/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('snippet-1.png' , size: '185x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header2'>Snippet</div>
  </header>
  <div class="items-sell-main">
  <h2 class="items-sell-title"><%= @snippet.group_name %></h2>
  <%= form_with model: [@snippet, @input_summary] , local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# 出品画像 %>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タブ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :summary_name, class:"items-text", id:"item-name", placeholder:"グループ名（必須 40文字まで)", maxlength:"40" %>
    </div>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "登録" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snippet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar"%>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <%# <div class='chat-room-form__field'>
    </div> %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.all.where.not(id: current_user.id).each do |user| %>
            <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("snippet-1.png",  size: '105x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header'>Snippet</div>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='search keyword'>
      <button class="search-button">
        <%= image_tag "icon-search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'menu', "#", class: "category-list" %></li>
      <li><%= link_to 'setting', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
      <li><%= link_to 'LogOut', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'LogIn', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'SignUp', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>

app/views/snippets/delete.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('snippet-1.png' , size: '185x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header2'>Snippet</div>
  </header>
  <div class="items-sell-main">
    <% if @snippet.user_id == current_user.id %>
      <h2 class="items-sell-title">本当に削除しますか？ </h2>
    <% else %>
      <h2 class="items-sell-title">削除したい場合は管理者に連絡してください</h2>
    <% end %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <% if @snippet.user_id == current_user.id %>
          <div class="form-input">
            <%= link_to '削除',snippet_path(@snippet.id), method: :delete , class: 'form-submit'  %>
          </div>
        <% end %>
        <div class="form-input">
          <%= link_to 'もどる', root_path, class:"back-submit" %>
        </div>
      </div>
      <%# /下部ボタン %>
  </div>
</div>

app/views/snippets/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('snippet-1.png' , size: '185x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header2'>Snippet</div>
  </header>
  <div class="items-sell-main">
  <h2 class="items-sell-title">スニペット編集</h2>
  <%= form_with model: @snippet , local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# 出品画像 %>

    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        グループ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :group_name, class:"items-text", id:"item-name", placeholder:"グループ名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "更新" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>

</div>

app/views/snippets/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='item-contents'>
    <h2 class='title'>Snippet</h2>
    <%= link_to '', class: "subtitle" %>
    <ul class='item-lists'>
      <% @snippets.each do |snippet|%>
      <li class='list'>
        <%= link_to snippet_input_summaries_path(snippet.id) do %>
        <div class='item-img-content'>
          <%= image_tag 'star-icon.png', class: "item-img" %>
          <div class='sold-out'>
            <span><%= snippet.group_name %></span>
          </div>
        </div>
        <% end %>
        <div class='item-info'>
          <%= link_to edit_snippet_path(snippet.id) do %>
            <div class='select-submit'>
              <%= "編集" %>
            </div>
          <% end %>
          <%= link_to delete_snippet_path(snippet.id) do %>
            <div class='select-submit'>
              <%= "削除" %>
            </div>
          <% end %>
        </div>
        
      </li>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_snippet_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>Make Up</span>
  <%= image_tag 'search-icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %> 

app/views/snippets/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('snippet-1.png' , size: '185x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header2'>Snippet</div>
  </header>
  <div class="items-sell-main">
  <h2 class="items-sell-title">スニペット登録</h2>
  <%= form_with model: @snippet , local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# 出品画像 %>

    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        グループ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :group_name, class:"items-text", id:"item-name", placeholder:"グループ名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "登録" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>
</div>

app/views/templates/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('snippet-1.png' , size: '185x50',class:"furima-icon"), "/" %>
    <div class='snippet-name-header2'>Snippet</div>
  </header>
  <div class="items-sell-main">
  <h2 class="items-sell-title">テンプレート</h2>
  <%= form_with model: [@input_summary, @template], local: true do |f| %>
    <%= render 'shared/error_messages', model: @template %>
    <%# 出品画像 %>

    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"グループ名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info",rows:"7" ,maxlength:"1000" %>
        <input value="<%= @template.id%>" type="hidden" name='template_id'>
      </div>
    </div>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "登録" ,class:"sell-btn" %>
        <%=link_to 'もどる', template_input_summary_path(@input_summary.id), class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>